In [5]:
import numpy as np
a = np.array([1, 2, 3, 3, 1, 6, 8, 11, 10, 7]).reshape(2, 5).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [10]:
mean_a = np.mean(a, axis=0)
mean_a

array([2. , 8.4])

In [14]:
np.tile(mean_a, (5,1))

array([[2. , 8.4],
       [2. , 8.4],
       [2. , 8.4],
       [2. , 8.4],
       [2. , 8.4]])

In [16]:
a_centered = a - np.tile(mean_a, (5,1))
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [22]:
a_centered_sp = np.sum(np.prod(a_centered, axis=1))
a_centered_sp / (5 - 1)

2.0

In [24]:
np.cov(a.T)[0,1]

2.0